# Generated by Django 4.1.1 on 2022-09-15 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact Name')),
                ('contact_title', models.CharField(max_length=255, verbose_name='Contact Title')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('region', models.CharField(max_length=255, verbose_name='Region')),
                ('postal_code', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('fax', models.CharField(max_length=255, verbose_name='Fax')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('title_of_courtesy', models.CharField(max_length=25, verbose_name='Title Of Courtesy')),
                ('birthday', models.DateField()),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('region', models.CharField(max_length=255, verbose_name='Region')),
                ('postal_code', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('home_page', models.CharField(max_length=255, verbose_name='Home Page')),
                ('extension', models.CharField(max_length=255, verbose_name='Extension')),
                ('photo', models.CharField(max_length=255, verbose_name='Photo')),
                ('notes', models.CharField(max_length=255, verbose_name='Notes')),
                ('reports_to', models.CharField(max_length=255, verbose_name='Reports To')),
            ],
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact Name')),
                ('contact_title', models.CharField(max_length=255, verbose_name='Contact Title')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('region', models.CharField(choices=[('SOUTH_SOUTH', 'South South'), ('SOUTH_WEST', 'South West'), ('SOUTH_EAST', 'South East'), ('NORTH_EAST', 'North East'), ('NORTH_WEST', 'North West'), ('NORTH_CENTRAL', 'North Central')], max_length=255, verbose_name='Regions')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('phone', models.PositiveBigIntegerField()),
                ('fax', models.PositiveSmallIntegerField()),
                ('home_page', models.CharField(max_length=255, verbose_name='Home Page')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('quantity_per_unit', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('units_in_stock', models.IntegerField()),
                ('units_on_order', models.IntegerField()),
                ('reorder_level', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium')], max_length=255, verbose_name='Reorder Level')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_process_app.category')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_process_app.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('required_date', models.DateTimeField()),
                ('shipped_date', models.DateTimeField(auto_now_add=True)),
                ('freight_date', models.PositiveBigIntegerField()),
                ('ship_name', models.CharField(max_length=255, verbose_name='Ship Name')),
                ('ship_Address', models.CharField(max_length=255, verbose_name='ShipAddress')),
                ('ship_city', models.CharField(max_length=255, verbose_name='Ship City')),
                ('ship_region', models.CharField(max_length=255, verbose_name='Ship Region')),
                ('ship_postal_code', models.PositiveSmallIntegerField()),
                ('ship_country', models.CharField(max_length=255, verbose_name='Ship Country')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_process_app.customers')),
                ('employees_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_process_app.employees')),
                ('shippers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_process_app.shippers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_process_app.orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_process_app.products')),
            ],
        ),
    ]
